controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /home
    controller: 'App\Controller\HomeController::index'
    
lucky_number:
    path: '/lucky/number'
    controller: 'App\Controller\LuckyController::number'
    methods: [GET]


product_show:
    path: '/product/{id}'
    controller: 'App\Controller\ProductController::show'
    methods: ['GET']
    requirements:
        id: '\d+'  

product_new:
    path: '/product/new'
    controller: 'App\Controller\ProductController::new'
    methods: ['GET', 'POST']

product_edit:
    path: '/product/{id}/edit'
    controller: 'App\Controller\ProductController::edit'
    methods: ['GET', 'POST']

product_delete:
    path: '/product/{id}/delete'
    controller: 'App\Controller\ProductController::delete'
    methods: ['POST']

products:
    path: /products
    controller: App\Controller\ProductController::listProducts
    methods: ['GET']

bouldering:
    path: /bouldering
    controller: App\Controller\ProductController::bouldering

team:
    path: /team
    controller: App\Controller\ProductController::team
    
about:
    path: /about
    controller: App\Controller\ProductController::about

app_login:
    path: /login
    controller: App\Controller\SecurityController::login